var spell_list = [{"school": "Necromancy", "name": "Abi-Dalzims Horrid Wilting", "level": "8th", "material": "* - a bit of sponge", "range": "150 ft(30 ft)", "components": "V, S, M", "duration": "Instantaneous", "cast_time": "1 Action", "save": "CON Save", "desc": "<p>You draw the moisture from every creature in a 30-foot cube centered on a point you choose within range. Each creature in that area must make a Constitution saving throw. Constructs and undead arent affected, and plants and water elementals make this saving throw with disadvantage. A creature takes 10d8 necrotic damage on a failed save, or half as much damage on a successful one.</p>"},
 {"school": "Abjuration", "name": "Absorb Elements", "level": "1st", "range": "Self", "components": "S", "duration": "1 Round", "cast_time": "1 Reaction  *", "save": "", "desc": "<p>The spell captures some of the incoming energy, lessening its effect on you and storing it for your next melee attack. You have resistance to the triggering damage type until the start of your next turn. Also, the first time you hit with a melee attack on your next turn, the target takes an extra 1d6 damage of the triggering type, and the spell ends.</p><p>At Higher Levels.When you cast this spell using a spell slot of 2nd level or higher, the extra damage increases by 1d6 for each slot level above 1st.</p>"},
 {"school": "Evocation", "name": "Acid Arrow", "level": "2nd", "material": "* - (powdered rhubarb leaf and an adder's stomach)", "range": "90 ft", "components": "V, S, M", "duration": "Instantaneous", "cast_time": "1 Action", "save": "Ranged", "desc": "<p>A shimmering green arrow streaks toward a target within range and bursts in a spray of acid. Make a ranged spell attack against the target. On a hit, the target takes 4d4 acid damage immediately and 2d4 acid damage at the end of its next turn. On a miss, the arrow splashes the target with acid for half as much of the initial damage and no damage at the end of its next turn.</p><p>At Higher Levels.When you cast this spell using a spell slot of 3rd level or higher, the damage (both initial and later) increases by 1d4 for each slot level above 2nd.</p>"},
 {"school": "Conjuration", "name": "Acid Splash", "level": "Cantrip", "range": "60 ft", "components": "V, S", "duration": "Instantaneous", "cast_time": "1 Action", "save": "DEX Save", "desc": "<p>You hurl a bubble of acid. Choose one creature within range, or choose two creatures within range that are within 5 feet of each other. A target must succeed on a Dexterity saving throw or take 1d6 acid damage.</p><p>This spells damage increases by 1d6 when you reach 5th level (2d6), 11th level (3d6), and 17th level (4d6).</p>"},
 {"school": "Evocation", "name": "Aganazzars Scorcher", "level": "2nd", "material": "* - a red dragon's scale", "range": "30 ft(30 ft)", "components": "V, S, M", "duration": "Instantaneous", "cast_time": "1 Action", "save": "DEX Save", "desc": "<p>A line of roaring flame 30 feet long and 5 feet wide emanates from you in a direction you choose. Each creature in the line must make a Dexterity saving throw. A creature takes 3d8 fire damage on a failed save, or half as much damage on a successful one.</p><p>At Higher Levels.When you cast this spell using a spell slot of 3rd level or higher, the damage increases by 1d8 for each slot level above 2nd.</p>"},
 {"school": "Abjuration", "name": "Aid", "level": "2nd", "material": "* - (a tiny strip of white cloth)", "range": "30 ft", "components": "V, S, M", "duration": "8 Hours", "cast_time": "1 Action", "save": "", "desc": "<p>Your spell bolsters your allies with toughness and resolve. Choose up to three creatures within range. Each target's hit point maximum and current hit points increase by 5 for the duration.</p><p>At Higher Levels.When you cast this spell using a spell slot of 3rd level or higher, a target's hit points increase by an additional 5 for each slot level above 2nd.</p>"},
 {"school": "Abjuration", "material": "* - (a tiny bell and a piece of fine silver wire)", "name": "Alarm", "level": "1st", "ritual": "yes", "range": "30 ft", "components": "V, S, M", "duration": "8 Hours", "cast_time": "1 Minute", "save": "", "desc": "<p>You set an alarm against unwanted intrusion. Choose a door, a window, or an area within range that is no larger than a 20-foot cube. Until the spell ends, an alarm alerts you whenever a Tiny or larger creature touches or enters the warded area. When you cast the spell, you can designate creatures that won't set off the alarm. You also choose whether the alarm is mental or audible.</p><p>A mental alarm alerts you with a ping in your mind if you are within 1 mile of the warded area. This ping awakens you if you are sleeping.</p><p>An audible alarm produces the sound of a hand bell for 10 seconds within 60 feet.</p>"},
 {"school": "Transmutation", "name": "Alter Self", "level": "2nd", "range": "Self", "components": "V, S", "duration": "1 Hour", "cast_time": "1 Action", "save": "", "concentration": "yes", "desc": "<p>You assume a different form. When you cast the spell, choose one of the following options, the effects of which last for the duration of the spell. While the spell lasts, you can end one option as an action to gain the benefits of a different one.</p><p>Aquatic Adaptation.You adapt your body to an aquatic environment, sprouting gills and growing webbing between your fingers. You can breathe underwater and gain a swimming speed equal to your walking speed.</p><p>Change Appearance.You transform your appearance. You decide what you look like, including your height, weight, facial features, sound of your voice, hair length, coloration, and distinguishing characteristics, if any. You can make yourself appear as a member of another race, though none of your statistics change. You also can't appear as a creature of a different size than you, and your basic shape stays the same; if you're bipedal, you can't use this spell to become quadrupedal, for instance. At any time for the duration of the spell, you can use your action to change your appearance in this way again.</p><p>Natural Weapons.You grow claws, fangs, spines, horns, or a different natural weapon of your choice. Your unarmed strikes deal 1d6 bludgeoning, piercing, or slashing damage, as appropriate to the natural weapon you chose, and you are proficient with your unarmed strikes. Finally, the natural weapon is magic and you have a +1 bonus to the attack and damage rolls you make using it.</p>"},
 {"school": "Enchantment", "name": "Animal Friendship", "level": "1st", "material": "* - (a morsel of food)", "range": "30 ft", "components": "V, S, M", "duration": "24 Hours", "cast_time": "1 Action", "save": "WIS Save", "desc": "<p>This spell lets you convince a beast that you mean it no harm. Choose a beast that you can see within range. It must see and hear you. If the beast's Intelligence is 4 or higher, the spell fails. Otherwise, the beast must succeed on a Wisdom saving throw or becharmedby you for the spell's duration. If you or one of your companions harms the target, the spells ends.</p><p>At Higher Levels.When you cast this spell using a spell slot of 2nd level or higher, you can affect one additional beast level above 1st.</p>"},
 {"school": "Enchantment", "material": "* - (a morsel of food)", "name": "Animal Messenger", "level": "2nd", "ritual": "yes", "range": "30 ft", "components": "V, S, M", "duration": "24 Hours", "cast_time": "1 Action", "save": "", "desc": "<p>By means of this spell, you use an animal to deliver a message. Choose a Tiny beast you can see within range, such as a squirrel, a blue jay, or a bat. You specify a location, which you must have visited, and a recipient who matches a general description, such as \"a man or woman dressed in the uniform of the town guard\" or \"a red-haired dwarf wearing a pointed hat.\" You also speak a message of up to twenty-five words. The target beast travels for the duration of the spell toward the specified location, covering about 50 miles per 24 hours for a flying messenger, or 25 miles for other animals.</p><p>When the messenger arrives, it delivers your message to the creature that you described, replicating the sound of your voice. The messenger speaks only to a creature matching the description you gave. If the messenger doesn't reach its destination before the spell ends, the message is lost, and the beast makes its way back to where you cast this spell.</p><p>At Higher Levels.If you cast this spell using a spell slot of 3rd level or higher, the duration of the spell increases by 48 hours for each slot level above 2nd.</p>"},
 {"school": "Transmutation", "name": "Animal Shapes", "level": "8th", "range": "30 ft", "components": "V, S", "duration": "24 Hours", "cast_time": "1 Action", "save": "", "concentration": "yes", "desc": "<p>Your magic turns others into beasts. Choose any number of willing creatures that you can see within range. You transform each target into the form of a Large or smaller beast with a challenge rating of 4 or lower. On subsequent turns, you can use your action to transform affected creatures into new forms.</p><p>The transformation lasts for the duration for each target, or until the target drops to 0 hit points or dies. You can choose a different form for each target. A target's game statistics are replaced by the statistics of the chosen beast, though the target retains its alignment and Intelligence, Wisdom, and Charisma scores. The target assumes the hit points of its new form, and when it reverts to its normal form, it returns to the number of hit points it had before it transformed. If it reverts as a result of dropping to 0 hit points, any excess damage carries over to its normal form. As long as the excess damage doesn't reduce the creature's normal form to 0 hit points, it isn't knocked unconscious. The creature is limited in the actions it can perform by the nature of its new form, and it can't speak or cast spells.</p><p>The target's gear melds into the new form. The target can't activate, wield, or otherwise benefit from any of its equipment.</p>"},
 {"school": "Necromancy", "name": "Animate Dead", "level": "3rd", "material": "* - (a drop of blood, a piece of flesh, and a pinch of bone dust)", "range": "10 ft", "components": "V, S, M", "duration": "Instantaneous", "cast_time": "1 Minute", "save": "", "desc": "<p>This spell creates an undead servant. Choose a pile of bones or a corpse of a Medium or Small humanoid within range. Your spell imbues the target with a foul mimicry of life, raising it as an undead creature. The target becomes askeletonif you chose bones or azombieif you chose a corpse (the GM has the creature's game statistics).</p><p>On each of your turns, you can use a bonus action to mentally command any creature you made with this spell if the creature is within 60 feet of you (if you control multiple creatures, you can command any or all of them at the same time, issuing the same command to each one). You decide what action the creature will take and where it will move during its next turn, or you can issue a general command, such as to guard a particular chamber or corridor. If you issue no commands, the creature only defends itself against hostile creatures. Once given an order, the creature continues to follow it until its task is complete.</p><p>The creature is under your control for 24 hours, after which it stops obeying any command you've given it. To maintain control of the creature for another 24 hours, you must cast this spell on the creature again before the current 24-hour period ends. This use of the spell reasserts your control over up to four creatures you have animated with this spell, rather than animating a new one.</p><p>At Higher Levels.When you cast this spell using a spell slot of 4th level or higher, you animate or reassert control over two additional undead creatures for each slot level above 3rd. Each of the creatures must come from a different corpse or pile of bones.</p>"},
 {"school": "Transmutation", "name": "Animate Objects", "level": "5th", "range": "120 ft", "components": "V, S", "duration": "1 Minute", "cast_time": "1 Action", "save": "", "concentration": "yes", "desc": "<p>Objects come to life at your command. Choose up to ten nonmagical objects within range that are not being worn or carried. Medium targets count as two objects, Large targets count as four objects, Huge targets count as eight objects. You can't animate any object larger than Huge. Each target animates and becomes a creature under your control until the spell ends or until reduced to 0 hit points.</p><p>As a bonus action, you can mentally command any creature you made with this spell if the creature is within 500 feet of you (if you control multiple creatures, you can command any or all of them at the same time, issuing the same command to each one). You decide what action the creature will take and where it will move during its next turn, or you can issue a general command, such as to guard a particular chamber or corridor. If you issue no commands, the creature only defends itself against hostile creatures. Once given an order, the creature continues to follow it until its task is complete.</p><p></p><p>An animated object is a construct with AC, hit points, attacks, Strength, and Dexterity determined by its size. Its Constitution is 10 and its Intelligence and Wisdom are 3, and its Charisma is 1. Its speed is 30 feet; if the object lacks legs or other appendages it can use for locomotion, it instead has a flying speed of 30 feet and can hover. If the object is securely attached to a surface or a larger object, such as a chain bolted to a wall, its speed is 0. It hasblindsightwith a radius of 30 feet and is blind beyond that distance. When the animated object drops to 0 hit points, it reverts to its original object form, and any remaining damage carries over to its original object form.</p><p>If you command an object to attack, it can make a single melee attack against a creature within 5 feet of it. It makes a slam attack with an attack bonus and bludgeoning damage determined by its size. The GM might rule that a specific object inflicts slashing or piercing damage based on its form.</p><p>At Higher Levels.If you cast this spell using a spell slot of 6th level or higher, you can animate two additional objects for each slot level above 5th.</p>"},
 {"school": "Abjuration", "name": "Antilife Shell", "level": "5th", "range": "Self(10 ft)", "components": "V, S", "duration": "1 Hour", "cast_time": "1 Action", "save": "", "concentration": "yes", "desc": "<p>A shimmering barrier extends out from you in a 10- foot radius and moves with you, remaining centered on you and hedging out creatures other than undead and constructs. The barrier lasts for the duration.</p><p>The barrier prevents an affected creature from passing or reaching through. An affected creature can cast spells or make attacks with ranged or reach weapons through the barrier.</p><p>If you move so that an affected creature is forced to pass through the barrier, the spell ends.</p>"},
 {"school": "Abjuration", "name": "Antimagic Field", "level": "8th", "material": "* - (a pinch of powdered iron or iron filings)", "range": "Self(10 ft)", "components": "V, S, M", "duration": "1 Hour", "cast_time": "1 Action", "save": "", "concentration": "yes", "desc": "<p>A 10-foot-radius invisible sphere of antimagic surrounds you. This area is divorced from the magical energy that suffuses the multiverse. Within the sphere, spells can't be cast, summoned creatures disappear, and even magic items become mundane. Until the spell ends, the sphere moves with you, centered on you.</p><p>Spells and other magical effects, except those created by an artifact or a deity, are suppressed in the sphere and can't protrude into it. A slot expended to cast a suppressed spell is consumed. While an effect is suppressed, it doesn't function, but the time it spends suppressed counts against its duration.</p><p>Targeted Effects.Spells and other magical effects, such asmagic missileandcharm person, that target a creature or an object in the sphere have no effect on that target.</p><p>Areas of Magic.The area of another spell or magical effect, such asfireball, can't extend into the sphere. If the sphere overlaps an area of magic, the part of the area that is covered by the sphere is suppressed. For example, the flames created by awall of fireare suppressed within the sphere, creating a gap in the wall if the overlap is large enough.</p><p>Spells.Any active spell or other magical effect on a creature or an object in the sphere is suppressed while the creature or object is in it.</p><p>Magic Items.The properties and powers of magic items are suppressed in the sphere. For example, alongsword, +1in the sphere functions as a nonmagical longsword.</p><p>A magic weapon's properties and powers are suppressed if it is used against a target in the sphere or wielded by an attacker in the sphere. If a magic weapon or a piece of magic ammunition fully leaves the sphere (for example, if you fire a magic arrow or throw a magic spear at a target outside the sphere), the magic of the item ceases to be suppressed as soon as it exits.</p><p>Magical Travel.Teleportation and planar travel fail to work in the sphere, whether the sphere is the destination or the departure point for such magical travel. A portal to another location, world, or plane of existence, as well as an opening to an extradimensional space such as that created by therope trickspell, temporarily closes while in the sphere.</p><p>Creatures and Objects.A creature or object summoned or created by magic temporarily winks out of existence in the sphere. Such a creature instantly reappears once the space the creature occupied is no longer within the sphere.</p><p>Dispel Magic.Spells and magical effects such asdispel magichave no effect on the sphere. Likewise, the spheres created by differentantimagic fieldspells don't nullify each other.</p>"},
 {"school": "Enchantment", "name": "Antipathy/Sympathy", "level": "8th", "material": "* - (either a lump of alum soaked in vinegar for the antipathy effect or a drop of honey for the sympathy effect)", "range": "60 ft(200 ft)", "components": "V, S, M", "duration": "10 Days", "cast_time": "1 Hour", "save": "WIS Save", "desc": "<p>This spell attracts or repels creatures of your choice. You target something within range, either a Huge or smaller object or creature or an area that is no larger than a 200-foot cube. Then specify a kind of intelligent creature, such as red dragons, goblins, or vampires. You invest the target with an aura that either attracts or repels the specified creatures for the duration. Choose antipathy or sympathy as the aura's effect.</p><p>Antipathy.The enchantment causes creatures of the kind you designated to feel an intense urge to leave the area and avoid the target. When such a creature can see the target or comes within 60 feet of it, the creature must succeed on a Wisdom saving throw or becomefrightened. The creature remainsfrightenedwhile it can see the target or is within 60 feet of it. Whilefrightenedby the target, the creature must use its movement to move to the nearest safe spot from which it can't see the target. If the creature moves more than 60 feet from the target and can't see it, the creature is no longerfrightened, but the creature becomesfrightenedagain if it regains sight of the target or moves within 60 feet of it.</p><p>Sympathy.The enchantment causes the specified creatures to feel an intense urge to approach the target while within 60 feet of it or able to see it. When such a creature can see the target or comes within 60 feet of it, the creature must succeed on a Wisdom saving throw or use its movement on each of its turns to enter the area or move within reach of the target. When the creature has done so, it can't willingly move away from the target.</p><p>If the target damages or otherwise harms an affected creature, the affected creature can make a Wisdom saving throw to end the effect, as described below.</p><p>Ending the Effect.If an affected creature ends its turn while not within 60 feet of the target or able to see it, the creature makes a Wisdom saving throw. On a successful save, the creature is no longer affected by the target and recognizes the feeling of repugnance or attraction as magical. In addition, a creature affected by the spell is allowed another Wisdom saving throw every 24 hours while the spell persists.</p><p>A creature that successfully saves against this effect is immune to it for 1 minute, after which time it can be affected again.</p>"},
 {"school": "Divination", "name": "Arcane Eye", "level": "4th", "material": "* - (a bit of bat fur)", "range": "30 ft", "components": "V, S, M", "duration": "1 Hour", "cast_time": "1 Action", "save": "", "concentration": "yes", "desc": "<p>You create an invisible, magical eye within range that hovers in the air for the duration.</p><p>You mentally receive visual information from the eye, which has normal vision anddarkvisionout to 30 feet. The eye can look in every direction.</p><p>As an action, you can move the eye up to 30 feet in any direction. There is no limit to how far away from you the eye can move, but it can't enter another plane of existence. A solid barrier blocks the eye's movement, but the eye can pass through an opening as small as 1 inch in diameter.</p>"},
 {"school": "Conjuration", "name": "Arcane Gate", "level": "6th", "range": "500 ft", "components": "V, S", "duration": "10 Minutes", "cast_time": "1 Action", "save": "", "concentration": "yes"},
 {"school": "Evocation", "name": "Arcane Hand", "level": "5th", "material": "* - (an eggshell and a snakeskin glove)", "range": "120 ft", "components": "V, S, M", "duration": "1 Minute", "cast_time": "1 Action", "save": "", "concentration": "yes", "desc": "<p>You create a Large hand of shimmering, translucent force in an unoccupied space that you can see within range. The hand lasts for the spell's duration, and it moves at your command, mimicking the movements of your own hand.</p><p>The hand is an object that has AC 20 and hit points equal to your hit point maximum. If it drops to 0 hit points, the spell ends. It has a Strength of 26 (+8) and a Dexterity of 10 (+0). The hand doesn't fill its space.When you cast the spell and as a bonus action on your subsequent turns, you can move the hand up to 60 feet and then cause one of the following effects with it.</p><p>Clenched Fist.The hand strikes one creature or object within 5 feet of it. Make a melee spell attack for the hand using your game statistics. On a hit, the target takes 4d8 force damage.</p><p>Forceful Hand.The hand attempts to push a creature within 5 feet of it in a direction you choose. Make a check with the hand's Strength contested by the Strength (Athletics) check of the target. If the target is Medium or smaller, you have advantage on the check. If you succeed, the hand pushes the target up to 5 feet plus a number of feet equal to five times your spellcasting ability modifier. The hand moves with the target to remain within 5 feet of it.</p><p>Grasping Hand.The hand attempts to grapple a Huge or smaller creature within 5 feet of it. You use the hand's Strength score to resolve the grapple. If the target is Medium or smaller, you have advantage on the check. While the hand is grappling the target, you can use a bonus action to have the hand crush it. When you do so, the target takes bludgeoning damage equal to 2d6 + your spellcasting ability modifier.</p><p>Interposing Hand.The hand interposes itself between you and a creature you choose until you give the hand a different command. The hand moves to stay between you and the target, providing you with half cover against the target. The target can't move through the hand's space if its Strength score is less than or equal to the hand's Strength score. If its Strength score is higher than the hand's Strength score, the target can move toward you through the hand's space, but that space is difficult terrain for the target.</p><p>At Higher Levels.When you cast this spell using a spell slot of 6th level or higher, the damage from the clenched fist option increases by 2d8 and the damage from the grasping hand increases by 2d6 for each slot level above 5th.</p>"},
 {"school": "Abjuration", "name": "Arcane Lock", "level": "2nd", "material": "* - (gold dust worth at least 25 gp, which the spell consumes)", "range": "Touch", "components": "V, S, M", "duration": "Until Dispelled", "cast_time": "1 Action", "save": "", "desc": "<p>You touch a closed door, window, gate, chest, or other entryway, and it becomes locked for the duration. You and the creatures you designate when you cast this spell can open the object normally. You can also set a password that, when spoken within 5 feet of the object, suppresses this spell for 1 minute. Otherwise, it is impassable until it is broken or the spell is dispelled or suppressed. Castingknockon the object suppressesarcane lockfor 10 minutes.</p><p>While affected by this spell, the object is more difficult to break or force open; the DC to break it or pick any locks on it increases by 10.</p>"}]

var height = 1000;

function test() {
    return $.getJSON('dnd_spells.json');
}

$.when(test()).then(function (d) {
    // localStorage["spell_list"] = JSON.stringify(d);
    // spell_list = JSON.parse(localStorage["spell_list"]);
    spell_list = d;
    console.log(spell_list);
    populateData();

});

// reveal the remaining part of the description
$('.row').delegate('.more', 'click', function () {
    console.log("more");
	$initPara = $(this).parent();
	$initPara.find('.more').html('');
	$initPara.remove('.more');

	var initText = $initPara.text();
	$remaining = $initPara.next();

    var endText = $remaining.html();
    var combined = "<p>" + initText + endText;

    $initPara.html(combined);
});

/*
    (C, R) Spell Name (9) - V,S,M                   Ranged Spell Attack / dexterity saving throw
    Range: ___                                                                      
    Casting Time                                                                        Duration
    School
    Description
    Material
*/
function populateData() {
    for (var i = spell_list.length - 1; i >= 0; i--) {
        var spell = spell_list[i];
        var text = spell.desc;
        var descFirst = '';
        var descLast = '';
        var desc = text;
        var material = "";
        if (text == null) { 
            text = ""; 
            desc = "<p>Check the Player's Handbook or elsewhere for details</p>";
        } else if (text.length > 100) {
            descFirst = text.substr(0, text.lastIndexOf(' ', 97)) + ' <a class="more">more...</a></p>';
            descLast = text.substr(text.lastIndexOf(' ', 97), text.length);

            desc = '' + descFirst + '<span class="remaining hidden">' + descLast.replace('\n', '</p><p>') + '</span>';
        } else {}

        if (spell.save == null) {
            spell.save = "";
        }

        var betw = "";
        if (spell.ritual == null) {
            spell.ritual = "";
        } else {
            spell.ritual = "R";
        }
        if (spell.concentration == null) {
            spell.concentration = "";
        } else {
            spell.concentration = "C";
        }
        if (spell.ritual != "" && spell.concentration != "") {
            betw = ", ";
        }
        if (spell.material != null) {
            material = spell.material;
        }

        // '<p>' + spell.description.replace('\n','</p><p>') + '</p>';
        var spellStr = "<li class=\"list-group-item loaded-spell\">\n" +
            "                <div class=\"row upper\">\n" +
            "                    <div class=\"hidden\" id=\"sp-name\">" + spell.name + "</div>\n" +
            "                    <h5>\n" +
            "                        <div class=\"col-sm-7\">" + spell.name + " (" + spell.level + ")</div>\n" +
            "                        <div class=\"col-sm-5 right-align\">" + spell.save + "</div>\n" +
            "                    </h5>\n" +
            "                </div>\n" +
            "                <div class=\"row middleOne\">\n" +
            "                    <div class=\"col-sm-7\">Range: " + spell.range + "</div>\n" +
            "                    <div class=\"col-sm-5 right-align\">" + spell.duration + "</div>\n" +
            "                </div>\n" +
            "                <div class=\"row middleTwo\">\n" +
            "                    <div class=\"col-sm-6\">" + spell.school + "</div>\n" +
            "                    <div class=\"col-sm-6 right-align\">" + spell.ritual + betw + spell.concentration + "</div>\n" +
            "                </div>\n" +
            "                <div class=\"row middleOne\">\n" +
            "                    <div class=\"col-sm-4\">" + spell.components + "</div>\n" +
            "                    <div class=\"col-sm-8 right-align\">" + material + "</div>\n" +
            "                </div>\n" +
            "                <div class=\"row description\">\n" +
            "                    <div class=\"col-sm-12\">\n" +
            "" + desc + "" +
            "                    </div>\n" +
            "                </div>\n" +
            "            </li>\n";

        $('#spells').append(spellStr);
    }
}

$(document).ready(function () {
    var height = $( document ).height();
    console.log(height);
    $("#spell-book").css("max-height", height + "px !important");

    spell_list = $.getJSON('dnd_spells.json');

    // var keys = Object.keys(localStorage),
    //     i = keys.length;
    // while ( i-- ) {
    //     localStorage.removeItem(keys[i]);
    // }
    // if (localStorage["spell_list"] != null) {
    //     spell_list = JSON.parse(localStorage["spell_list"]);
    // }
});